language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
nodejs:
  - "8.7.0"
cache:
  pip: true
  directories:
    - node_modules
install:
  - pip install -U pip setuptools wheel
  - pip install tox-travis codecov
  - nvm install 8
  - npm i
  - npm run build-assets --production
  - npm run build-emails
  - npm run test
script:
  - tox
  exclude:
    - nodejs: "8.7.0"
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
    - DATABASE_URL='postgres://postgres@localhost:5432/saleor'
  matrix:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="master"
matrix:
  allow_failures:
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="master"
  exclude:
    - python: "3.4"
      env: DJANGO="master"
    - nodejs: "8.7.0"
after_success:
  - codecov
services:
  - postgresql
  exclude:
    - nodejs: "8.7.0"
