apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "saleor.fullname" . }}-celery-worker
  labels:
    app: {{ template "saleor.name" . }}
    chart: {{ template "saleor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "saleor.name" . }}-celery-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "saleor.name" . }}-celery-worker
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      volumes:
        - name: custom-settings
          configMap:
          {{- if (not .Values.django.alternativeConfigMap) }}
            name: saleor-custom-settings
          {{- else }}
            name: {{ .Values.django.alternativeConfigMap }}
          {{- end }}
        - name: saleor-data
        # TODO Introduce another conditional for when one is using S3 based storage
        {{- if and (eq .Values.persistence.enabled true) (.Values.persistence.existingClaim) }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if (eq .Values.persistence.enabled true) }}
          persistentVolumeClaim:
            claimName: {{ default (include "saleor.fullname" .) }}
        {{- else }}
          emptyDir:
            medium: Memory
        {{- end }}
      # TODO Introduce a conditional for /app/media when one is using S3 based storage
      initContainers:
        - name: {{ template "saleor.fullname" . }}-celery-worker-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["chown", "-R", "saleor:saleor", "/app/media"]
          volumeMounts:
            - name: saleor-data
              mountPath: /app/media
          securityContext:
            runAsUser: 0
            privileged: true
      containers:
        - name: {{ template "saleor.fullname" . }}-celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          command: ["sleep", "1000s"]
          command: ["celery", "worker"]
          args:
            - --app=saleor.celeryconf:app
            - --without-gossip
            - --without-mingle
            - --heartbeat-interval={{ .Values.celery.heartBeatIntervalSeconds }}
            - --loglevel={{ .Values.celery.logLevel }}
          {{- if (eq (.Values.celery.concurrencyType) "fixed") }}
            - --concurrency={{ .Values.celery.fixedConcurrency }}
          {{- else if (eq (.Values.celery.concurrencyType) "auto") }}
            - --autoscale={{ .Values.celery.maxConcurrency }},{{ .Values.celery.minConcurrency }}
          {{- end }}
          {{- if (.Values.celery.hardTimeLimitSeconds) }}
            - --time-limit={{ .Values.celery.hardTimeLimitSeconds }}
          {{- end }}
          {{- if (.Values.celery.softTimeLimitSeconds) }}
            - --soft-time-limit={{ .Values.celery.softTimeLimitSeconds }}
          {{- end }}
          {{- if (eq .Values.celery.taskEventsMonitoringEnabled true) }}
            - --task-events
          {{- end }}
#          livenessProbe:
#          readinessProbe:
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            # TODO Introduce a conditional for /app/media when one is using S3 based storage
            - name: saleor-data
              mountPath: /app/media
            - name: custom-settings
              mountPath: /app/saleor/custom-settings.py
              subPath: custom-settings.py
              readOnly: true

          envFrom:
          {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- else }}
            - secretRef:
                name: {{ template "saleor.fullname" . }}-secrets
          {{- end }}
            - configMapRef:
                name: {{ template "saleor.fullname" . }}-env-{{ .Release.Namespace }}
          env:
          {{ if and (eq .Values.postgresql.enabled true) (eq .Values.postgresql.useExternalUrl false)  }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.postgresql.existingSecret }}
                  name: {{ .Values.postgresql.existingSecret }}
                {{- else }}
                  name: {{ .Release.Name }}-postgresql
                {{- end }}
                  key: postgres-password
          {{- end }}
          {{ if and (eq .Values.redis.enabled true) (eq .Values.redis.usePassword true) (eq .Values.redis.useExternalUrl false) }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.existingSecret }}
                  name: {{ .Values.redis.existingSecret }}
                {{- else }}
                  name: {{ .Release.Name }}-redis
                {{- end }}
                  key: redis-password
          {{- end }}

            - name: DATABASE_URL
              value: "postgres://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_HOST):$(POSTGRESQL_PORT)/$(POSTGRESQL_DATABASE)"

          {{- if and (eq .Values.elasticsearch.enabled true) (eq .Values.elasticsearch.useExternalUrl false) }}
            - name: ELASTICSEARCH_URL
              value: "http://$(ELASTICSEARCH_HOST):$(ELASTICSEARCH_PORT)"
          {{- else if (eq .Values.elasticsearch.useExternalUrl true) }}
            - name: ELASTICSEARCH_URL
              value: "https://$(ELASTICSEARCH_USER):$(ELASTICSEARCH_PASSWORD)@$(ELASTICSEARCH_HOST):$(ELASTICSEARCH_PORT)"
          {{- end }}

            - name: REDIS_URL
          {{- if or (eq .Values.redis.useExternalUrl true) (eq .Values.redis.usePassword true) }}
              value: "redis://$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/$(REDIS_DB_NUMBER)"
          {{- else }}
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/$(REDIS_DB_NUMBER)"
          {{- end }}

            - name: CELERY_BROKER_URL
          {{- if or (eq .Values.redis.useExternalUrl true) (eq .Values.redis.usePassword true) }}
              value: "redis://$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/$(CELERY_BROKER_DB_NUMBER)"
          {{- else }}
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/$(CELERY_BROKER_DB_NUMBER)"
          {{- end }}
          resources:
{{ toYaml .Values.celery.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.celery.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.celery.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
