---
{{- if (not .Values.django.alternativeConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: saleor-custom-settings
  namespace: {{ .Release.Namespace }}
data:
  custom-settings.py: |
    from saleor.settings import *

{{- if eq (len .Values.django.admins) 0 -}}
    ADMINS = ()
{{- else }}
    ADMINS = (
    {{- range .Values.django.admins }}
        ('{{ .name }}', '{{ .email }}'),
    {{- end }}
    )
{{- end }}
    MANAGERS = ADMINS

    INTERNAL_IPS = get_list(
        os.environ.get('INTERNAL_IPS', '127.0.0.1'))

    TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')
    LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en')
    USE_I18N = get_bool_from_env('USE_I18N', True)
    USE_L10N = get_bool_from_env('USE_L10N', True)
    USE_TZ = get_bool_from_env('USE_TZ', True)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'root': {
            'level': os.environ.get('ROOT_LOG_LEVEL', 'INFO'),
            'handlers': ['console']},
        'formatters': {
            'verbose': {
                'format': (
                    '%(levelname)s %(name)s %(message)s'
                    ' [PID:%(process)d:%(threadName)s]')},
            'simple': {
                'format': '%(levelname)s %(message)s'}},
        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse'}},
        'handlers': {
            'mail_admins': {
                'level': os.environ.get('MAIL_ADMINS_HANDLER_LEVEL', 'ERROR'),
                'filters': ['require_debug_false'],
                'class': 'django.utils.log.AdminEmailHandler'},
            'console': {
                'level': os.environ.get('CONSOLE_HANDLER_LEVEL', 'DEBUG'),
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'}},
        'loggers': {
            'django': {
                'handlers': ['console', 'mail_admins'],
                'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': True},
            'django.server': {
                'handlers': ['console'],
                'level': os.environ.get('DJANGO_SERVER_LOG_LEVEL', 'INFO'),
                'propagate': True},
            'saleor': {
                'handlers': ['console'],
                'level': os.environ.get('SALEOR_LOG_LEVEL', 'DEBUG'),
                'propagate': True}}}
    if "AVAILABLE_CURRENCIES" in os.environ:
        AVAILABLE_CURRENCIES = get_list(os.environ.get('AVAILABLE_CURRENCIES'))
    else:
        AVAILABLE_CURRENCIES = [os.environ.get('DEFAULT_CURRENCY', 'USD')]
    LOGIN_REDIRECT_URL = os.environ.get('LOGIN_REDIRECT_URL', 'home')
    LOW_STOCK_THRESHOLD = int(os.environ.get('LOW_STOCK_THRESHOLD', 10))
    PAGINATE_BY = int(os.environ.get('PAGINATE_BY', 16))
    DASHBOARD_PAGINATE_BY = int(os.environ.get('DASHBOARD_PAGINATE_BY', 30))
    DASHBOARD_SEARCH_LIMIT = int(os.environ.get('DASHBOARD_SEARCH_LIMIT', 5))
    PLACEHOLDER_IMAGES = {
        60: os.environ.get('PLACEHOLDER_IMAGE_60', 'images/placeholder60x60.png'),
        120: os.environ.get('PLACEHOLDER_IMAGE_120', 'images/placeholder120x120.png'),
        255: os.environ.get('PLACEHOLDER_IMAGE_255', 'images/placeholder255x255.png'),
        540: os.environ.get('PLACEHOLDER_IMAGE_540', 'images/placeholder540x540.png'),
        1080: os.environ.get('PLACEHOLDER_IMAGE_1080', 'images/placeholder1080x1080.png')}
    DEFAULT_PLACEHOLDER = PLACEHOLDER_IMAGES[255]
    LOGOUT_ON_PASSWORD_CHANGE = get_bool_from_env('LOGOUT_ON_PASSWORD_CHANGE', False)
    DB_SEARCH_ENABLED = get_bool_from_env('DB_SEARCH_ENABLED', True)
{{- end -}}
