{{- if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "saleor.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "saleor.name" . }}
    chart: {{ template "saleor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 50 | b64enc | quote }}
  EMAIL_PASSWORD:
  RECAPTCHA_PRIVATE_KEY:
  OPENEXCHANGERATES_API_KEY:
  VATLAYER_ACCESS_KEY:

  # Only required if .Values.aws.enabled: true
  #  AWS_ACCESS_KEY_ID:
  #  AWS_SECRET_ACCESS_KEY:

  # Set only if .Values.redis.useExternalUrl: true
  #  REDIS_PASSWORD:
  #  REDIS_HOST:
  #  REDIS_PORT:
  #  REDIS_DB_NUMBER: "0"
  #  CELERY_BROKER_DB_NUMBER: "1"

  # Set only if .Values.postgresql.useExternalUrl: true
  #  POSTGRESQL_PASSWORD:
  #  POSTGRESQL_USER:
  #  POSTGRESQL_HOST:
  #  POSTGRESQL_PORT:
  #  POSTGRESQL_DATABASE:

  # Set only if .Values.elasticsearch.useExternalUrl: true
  #  ELASTICSEARCH_PASSWORD:
  #  ELASTICSEARCH_USER:
  #  ELASTICSEARCH_HOST:
  #  ELASTICSEARCH_PORT:

{{- end }}

