name: GraphQL Inspector

on:
  push:
    paths: [ "**.graphql" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: graphql-hive/graphql-inspector@release-1769448022768
        with:
          schema: "main:saleor/graphql/schema.graphql"
