name: GraphQL Inspector

on:
  push:
    paths: [ "**.graphql" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "main:saleor/graphql/schema.graphql"
