name: Notify Discord on Help Wanted Issue

on:
  issues:
    types: [labeled]

jobs:
  notify:
    if: github.event.label.name == 'help wanted'
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: appleboy/discord-action@6047e1fe519c24dbf2865cf0557f20f51f075b3e # v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_GFI_WEBHOOK_URL }}
          message: |
            ğŸ‰ New Issue Labeled with "Help Wanted" in Saleor Core

            **Issue Details:**
            - Title: ${{ github.event.issue.title }}
            - Number: #${{ github.event.issue.number }}
            - URL: ${{ github.event.issue.html_url }}

            Please take a look and help if you can! ğŸ™
