name: Test Semgrep Rules
on:
  push:
    paths:
      - .semgrep/**
      - .github/workflows/test-semgrep-rules.yml
  pull_request:
    paths:
      - .semgrep/**
      - .github/workflows/test-semgrep-rules.yml

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          sparse-checkout: |
            .semgrep

      - name: Install Dependencies
        run: python3 -m pip install semgrep==1.39.0

      - name: Run Tests
        working-directory: .semgrep
        run: make test
